### PR TITLE
doc: add completeness to requirements

### PR DESCRIPTION
**Pull request by yulaseo**
Issue #34

### CODE REVIEW

**Review by d0lim — APPROVED** [review]
LGTM. Approved.

I found out that my pr that fixes #30 is not merged properly. Will open pr again.

**Comment by cjdthsus2gh** [comment]
Approved.

**Review by Beopsik — APPROVED** [review]
Approved

**Review by cjdthsus2gh — APPROVED** [review]
Approved.

**Review by pjs0418 — APPROVED** [review]

**Review by youngkwon02 — APPROVED** [review]
Approve

**Pull request merged**
