### PR TITLE
doc: fix issue #30

### LINKED ISSUE #30: [원자성 검토] 원자성 검토 사항
REQ-5 : The system should allow a manager to search guest with guest's ID or name.   
---
- The system should allow a manager to search guest with guest's ID.  
- The system should allow a manager to search guest with guest's name.   
---

REQ-41 : The system shall notify to guests through SMS or E-mail when due date approaches.  
---
- The system shall notify to guests through SMS when due date approaches.  
- The system shall notify to guests through E-mail when due date approaches.  
---

REQ-42 : The system shall allow guests to send feedback with contents anonymously or not.  
---
- The system shall allow guests to send feedback with contents anonymously.
- The system shall allow guests to send feedback with contents non-anonymously.  
---

### PR DESCRIPTION
**Pull request by d0lim**
Found that my PR was not merged properly that fix issue #30.

### CODE REVIEW

**Review by Beopsik — APPROVED** [review]
Approved

**Review by yulaseo — APPROVED** [review]

**Comment by pjs0418** [comment]
37번 자동 반납에 대한 내용 누락되었습니다.

**Review by pjs0418 — APPROVED** [review]
Approved

**Review by cjdthsus2gh — APPROVED** [review]
Approved.

**Review by youngkwon02 — APPROVED** [review]

**Pull request merged**
